name: Convert Markdown to PDF
on:
  push:
    paths:
      - '**.md'
      
jobs:
  convert_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install md-to-pdf
        run: npm install -g md-to-pdf
        
      - name: Convert MD to PDF
        run: |
          for file in $(find . -name "*.md" -not -path "./node_modules/*" -not -path "./.git/*"); do
            md-to-pdf $file
          done
          
      - name: Commit PDF files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.pdf
          git commit -m "Convert MD to PDF" || true
          git push